export const GET_SELECT_GAME_DATA_SUCCESS = 'GET_SELECT_GAME_DATA_SUCCESS';
export const GET_SELECT_GAME_DATA_FAIL = 'GET_SELECT_GAME_DATA_FAIL';
export const CREATE_GAME_DATA_SUCCESS = 'CREATE_GAME_DATA_SUCCESS';
export const CREATE_GAME_DATA_FAIL = 'CREATE_GAME_DATA_FAIL';
export const SET_USER_GAME_DATA_SUCCESS = 'CREATE_GAME_DATA_SUCCESS';
export const SET_USER_GAME_DATA_FAIL = 'CREATE_GAME_DATA_FAIL';